document: feedback-pipeline-workload
version: 1
data:
  name: Traditional X11 environment
  description: Libraries and sample applications historically provided with an X11 installation
  maintainer: sst_graphics_infrastructure

  packages:
    - libXaw
    - mesa-libGLw
    - mesa-libGLU
    - xrestop
    - libXp
    # No-ops in terms of functionality, just ABI compat purposes
    - libXScrnSaver
    - libXvMC
    - libXxf86dga
    - libXxf86misc
    ##############
  labels:
    - eln
